// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqystivdecrjuulxyxet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxeXN0aXZkZWNyanV1bHh5eGV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNzk0NDQsImV4cCI6MjA2NzY1NTQ0NH0.k5yyzWEhK17narXB6VSA6rTBMOP929lQcWqr21Z8C2g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});